# Generated by Django 4.2.6 on 2023-11-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menuitem')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
